[ADD] get photo
Immobylette/immobylette--api-photo pull request #1
Opened 2024-05-04 13:24 UTC by patacoing

Petit point bizarre : 
dans le application.yml si on veut fournir le chemin du fichier, il faut mettre en valeur  par défaut, le chemin absolue. Je comprends pas trop pq, mais ducoup ça fonctionne.

Le fichier est à mettre dans src/main/resources

J'ai mis 1min en temps de validité de l'url parce que on pas besoin de plus, quand le client la récupère, il l'affiche l'image reste affichée même après une minute.

Note : 
- dans PhotoDto j'ai du mettre des @JsonProperty partout parce que sinon il considéré que ma répoonse était pas un json et ducoup le client reçoit une 406 même en ayant Accept: */*

2024-05-04 13:25 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implémenter la feature Photo](https://trello.com/c/tMEKF5gy/69-impl%C3%A9menter-la-feature-photo)

2024-05-05 15:07 UTC, OdakK requested changes

2024-05-05 15:07 UTC, OdakK commented on src/main/java/com/immobylette/api/photo/util/GCPStorage.java
> +            @Value("${spring.gcp.project-id}") String projectId,
Créer un fichier de config GCSconfig.java avec les credentias

2024-05-05 15:07 UTC, OdakK commented on src/main/java/com/immobylette/api/photo/util/GCPStorage.java
> +    public URL getSignedUrl(String objectName) throws StorageException {
Mettre les méthodes dans une classe dans ressource, elle contiendra les actions que l'on veut faire sur le bucket (upload, delete, download, getSigned etc..)

2024-05-07 18:50 UTC, LfrPaul approved these changes

2024-05-09 10:48 UTC, OdakK approved these changes

2024-05-09 10:48 UTC, OdakK commented on src/main/java/com/immobylette/api/photo/resource/GCS.java
> +public class GCS {
Rename GCSResource

2024-05-09 12:49 UTC, merged