[ADD] folder feature
Immobylette/immobylette--api-photo pull request #4
Opened 2024-05-13 18:34 UTC by OdakK

2024-05-13 18:35 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implémenter la feature Folder](https://trello.com/c/kuWd8L7y/70-impl%C3%A9menter-la-feature-folder)

2024-05-13 20:15 UTC, patacoing requested changes

2024-05-14 11:37 UTC, patacoing approved these changes

2024-05-15 14:20 UTC, LfrPaul approved these changes

2024-05-15 17:04 UTC, merged