cicd: add github action for cicd
Immobylette/immobylette--api-photo pull request #5
Opened 2024-05-15 21:57 UTC by OdakK

2024-05-16 11:18 UTC, patacoing requested changes

2024-05-16 11:18 UTC, patacoing commented on .github/workflows/maven.yml
> +          prefix=$(echo "${{ github.event.head_commit.message }}" | cut -d'/' -f 1)")
utiliser plutôt : git show -s --format=%s

parce que lorsque l'on fait un squash and merge, on a 2 messages : 
- le header
- le contenu

et ce contenu peut contenir la liste des commits réalisés. Et la variable que tu utilises, combine le header ainsi que le contenu donc le cut ne fonctionne pas.

la modif que je propose est celle présente dans la ci/cd de l'api main et de l'app mobile et ne récupère que le header

2024-05-16 11:18 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [CI/CD sur l'api Photo](https://trello.com/c/szUse35F/67-ci-cd-sur-lapi-photo)

2024-05-16 19:23 UTC, patacoing approved these changes

2024-05-17 14:15 UTC, LfrPaul approved these changes

2024-05-19 17:33 UTC, AlexisPop approved these changes

2024-05-20 11:18 UTC, merged