[ADD] Upload folder
Immobylette/immobylette--api-photo pull request #9
Opened 2024-05-22 17:19 UTC by LfrPaul

Create folder in BDD
Create all photos in BDD
Upload each photo in bucket

2024-05-22 17:19 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Upload un folder](https://trello.com/c/YXmrKOwW/110-upload-un-folder)

2024-05-23 13:29 UTC, patacoing requested changes

2024-05-23 13:29 UTC, patacoing commented on src/main/java/com/immobylette/api/photo/controller/FolderController.java
> +    public UUID addStep(@RequestPart("photos") List<MultipartFile> photos,
ne pas l'appeler addStep car le service de photos n'a pas conscience qu'il est utilisé seulement par l'api main, il pourrait très bien être appelé par un autre service

2024-05-23 13:29 UTC, patacoing commented on src/main/java/com/immobylette/api/photo/resource/GCSResource.java
> +    public void uploadFile(Storage storageClient, String fileName, MultipartFile file) throws IOException {
pas besoin d'importer storageClient car on l'a déjà dans l'instance de la classe (prop storage)

2024-05-23 13:29 UTC, patacoing commented on src/main/java/com/immobylette/api/photo/service/PhotoService.java
> +    Storage storageClient;
pas besoin de ce prop

2024-05-23 13:29 UTC, patacoing commented on src/main/java/com/immobylette/api/photo/service/FolderService.java
> +        while (photoIterator.hasNext() && descriptionIterator.hasNext()) {
est-ce qu'on ne devrait pas tester si les deux iterator sont de la même taille ? et si ce n'est pas le cas, renvoyer une 400 ?

2024-05-25 12:52 UTC, patacoing approved these changes

2024-05-28 17:20 UTC, OdakK approved these changes

2024-05-29 16:29 UTC, merged